### ISSUE TITLE
[Proposal] Archive the list of chapters by a given author rather than just linking to writing.com (which doesn't work for deleted authors)

### ISSUE THREAD

**Issue by NintendoManiac64** [Ackater/writing.com-archival#50]
Currently, if an author has had their account deleted, then clicking the author link in your archive doesn't exactly help despite your writing.com archive clearly being able to record who the author was from before their account was deleted.

Therefore, I propose that the list of chapters by a given author also be archived since, in theory, all of that information is already actually archived but just isn't organized and sorted together.

As a bonus, this would additionally provide a functional benefit greater than what a premium writing.com account could even provide since, on writing,com, chapters written by a deleted author are listed as simply having no author.

Here's an example of a deleted author if you need it (NSFW + weirdness warning)
https://www.writing.com/main/portfolio/view/yearends
https://www.writing.com/main/view_item/action/show_chapters/user_id/yearends

And two examples of chapters they wrote (again, NSFW + weirdness warning):
https://www.writing.com/main/interactive-story/item_id/1920309-I-am-X-Almighty/map/122
https://www.writing.com/main/interactive-story/item_id/1920309-I-am-X-Almighty/map/1221

...and the equivalent archived versions of those two aforementioned chapters along with several more by the same author (once again, NSFW + weirdness warning):
https://ackater.github.io/writing.com-archival/#/1920309-I-am-X-Almighty-/122

**Comment by Ackater** [comment]
You're right, it is pretty useless. Simple enough to add, so here we go: https://ackater.github.io/writing.com-archival/#/1920309-I-am-X-Almighty-/author/yearends

It'll be per story: searching between stories would be difficult with the way the database is setup. Also because deleted authors do not show up in chapters, the database is incomplete with some chapters missing authors.

**Comment by Ackater** [comment]
The search bar should already search for authors when searching.

**Comment by NintendoManiac64** [comment]
It only seems to search for stories by an author rather than individual chapters though.

**Comment by Ackater** [comment]
Oh yeah it's by the story's author, not by individual chapter author. With the way the website is setup, where you download the entire list of stories on load, and when you load a story it downloads the entire thing, I don't really want to add more data because then it'll take longer to load. 

Loading times are already pretty noticeable with longer stories as it is now.

**Comment by NintendoManiac64** [comment]
So uh, I guess there's nothing more we can do here then?

If that's the case, I have a minor request - can you edit out the URL in your comment from Oct 4, 2022?

Basically I don't actually want any lasting NSFW stuff associated with this github account of mine, but I also really didn't want to create a whole separate account just to inquire about this deleted author issue.

...and it'd probably be best that, if you make a final follow-up comment, to keep it simple since I'll likely be editing some of my comments here rather heavily, similarly removing the NSFW references and such.

**Comment by Ackater** [comment]
Yeah won't be added until I migrate the database to a proper database, which may or may not happen. So I think we can close the issue

**Comment by NintendoManiac64** [comment]
Alright then.

Note that I've archived this issue in the usual places for archiving webpages before making my edits.
